#!/usr/bin/env node

/*
  Test a channel by simulating the execution of triggers, status,
  and other IFTTT API calls.
*/

var fs = require("fs"),
    request = require('request');


var Channel = {


  /******* test methods *****/

  // status endpoint
  // https://ifttt.com/developers/docs/protocol_reference#channel-status
  status: function(args) {
    Channel.get("/ifttt/v1/status");
  },

  // check a trigger.
  // required:
  //   --trigger: trigger slug
  // optional:
  //   --limit: max number of items to be returned (num)
  //   --before: return items before this time (string)
  //   --after: return items after this time (string)
  //   --triggerFields: trigger fields (object)
  // https://ifttt.com/developers/docs/protocol_reference#triggers
  trigger: function(args) {
    if (!args.trigger) return console.log("Specify a --trigger.");

    var body = {};
    if (args.fields) body.triggerFields = args.fields;
    if (args.limit) body.limit = args.limit;
    if (args.before) body.before = Channel.time(args.before);
    if (args.after) body.before = Channel.time(args.after);

    Channel.post("/ifttt/v1/triggers/" + args.trigger, body);
  },

  // dynamic trigger field options.
  // required:
  //   --trigger: trigger slug
  //   --field: field slug
  // https://ifttt.com/developers/docs/protocol_reference#trigger-field-dynamic-options
  trigger_options: function(args) {
    if (!args.trigger) return console.log("Specify a --trigger.");
    if (!args.field) return console.log("Specify a --field.");

    Channel.post("/ifttt/v1/triggers/" + args.trigger + "/fields/" + args.field + "/options");
  },

  // dynamic trigger field options.
  // required:
  //   --trigger: trigger slug
  //   --field: field slug
  //   --value: field value
  // https://ifttt.com/developers/docs/protocol_reference#trigger-field-dynamic-validation
  trigger_validate: function(args) {
    if (!args.trigger) return console.log("Specify a --trigger.");
    if (!args.field) return console.log("Specify a --field.");

    var body = {value: args.value};
    Channel.post("/ifttt/v1/triggers/" + args.trigger + "/fields/" + args.field + "/validate", body);
  },


  /******* utility methods, used by tests *****/

  // workhorse request method, output what is being done.
  request: function(method, url, body) {
    // default to http:// if no protocol given
    var host = Channel.host;
    if (Channel.host.search(/^https?:\/\//) < 0)
      host = "http://" + host;
    var url = host + url;

    // always expect json in return
    var options = {method: method, url: url, json: true};

    console.log(method + ": " + url);

    if (body) {
      console.log("With: " + Channel.pp(body));
      options.json = body;
    }

    request(options, function (error, response, body) {
      if (error) return console.log("ERROR: " + error);

      console.log("Status: " + response.statusCode);
      if (body) console.log("\n" + Channel.pp(body));
    });
  },

  get: function(url) {return Channel.request("GET", url)},
  post: function(url, body) {return Channel.request("POST", url, body)},

  pp: function(object) {return JSON.stringify(object, null, 4)},
  time: function(timestamp) {
    // assume any epoch time passed in via CLI is in seconds
    if (typeof(timestamp) == "number")
      timestamp = timestamp * 1000;

    return new Date(timestamp).getTime() / 1000;
  },

  host: null,

  config: {
    // get the whole config file
    get: function() {
      if (fs.existsSync(Channel.config.filename))
        return JSON.parse(fs.readFileSync(Channel.config.filename));
      else
        return {};
    },

    set: function(key, value) {
      var config = Channel.config.get();
      config[key] = value;

      var data = JSON.stringify(config, null, 2) + "\n";
      fs.writeFileSync(Channel.config.filename, data);
    },

    filename: process.env.HOME + "/.ifttt"
  }
};


/******* tiny CLI *****/


// $HOME/.ifttt is an optional JSON config file for default parameters.
//
// supported parameters: host

var config = Channel.config.get();


var optimist = require('optimist');
var args = optimist
  .alias("field", "f")
  .alias("trigger", "t")
  .describe("field", "Field slug to be simulated.")
  .describe("trigger", "Trigger slug to be simulated.")
  .usage("iftttest [HOST] COMMAND [options]\n\n" +
      "HOST is the base hostname of the channel.\n\n" +
      "COMMAND is one of:\n  status, trigger, trigger_options, trigger_validate\n\n" +
      "You can omit HOST by setting a default:\n" +
      "  iftttest set host [host]")
  .argv;

if (args.help) {
  console.log(optimist.help());
  process.exit(0);
}

// --args: debug to understand how args get parsed
if (args.args) {
  console.log("args: " + Channel.pp(args));
  process.exit(0);
}

// special command: `set` will set a value in $HOME/.ifttt
if (args._[0] == "set") {
  var key = args._[1];
  var value = args._[2];

  console.log("Setting `" + key + "` to `" + value + "`");
  Channel.config.set(key, value);

  process.exit(0);
}


// interpret as HOST COMMAND if no host set, COMMAND otherwise
var host = config.host || args._.shift();
var command = args._.shift();

if (!host || !command) {
  console.log(optimist.help());
  process.exit(1);
}


Channel.host = host;
Channel[command](args);